on:
  push:
    branches:
      - "main"
    paths:
      - 'website/*'
  workflow_dispatch:
    branches:
      - "main"
      - "dev"

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
      
jobs:
  deploy:
    name: Update contreras.io website
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ACTION }}
        aws-region: us-west-1
  
    - name: test echos
      run: |
        echo "here is bucket name: ${{env.S3_BUCKET_NAME}}"
        echo "here is bucket name: $S3_BUCKET_NAME"
        echo "variable from shell environment : $env_var"
      env:
        S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}

    - name: Update Website by Sync
      run: aws s3 sync ./website/ s3://${{env.S3_BUCKET_NAME}} --delete
      env:
        S3_BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}