on:
  push:
    branches:
      - "main"
    paths:
      - 'website/*'
  workflow_dispatch:
    branches:
      - "main"
  
jobs:
  deploy:
    name: Update contreras.io website
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ACTION }}
        aws-region: us-west-1
        

    - name: Update Website by Sync
      run: aws s3 sync ./website/ s3://${{env.S3_BUCKET_NAME}} --delete